import type { Category, Gender, Product } from "./types";

const DEFAULT_TEE_PRICE = 24.9;
const SIZES_APPAREL = ["XS", "S", "M", "L", "XL"];
const SIZES_KIDS = ["2A", "4A", "6A", "8A", "10A", "12A"];
const SIZES_SHOES = ["39", "40", "41", "42", "43", "44", "45"];
const SIZES_KIDS_SHOES = ["28", "30", "32", "34", "36"];

const C = {
  white: { name: "Blanc", hex: "#FFFFFF" },
  black: { name: "Noir", hex: "#111111" },
  navy: { name: "Bleu Marine", hex: "#0F1F3D" },
  grey: { name: "Gris", hex: "#A0A0A0" },
  cream: { name: "Crème", hex: "#F5EFE0" },
  beige: { name: "Beige", hex: "#D8C7A6" },
  brown: { name: "Marron", hex: "#5B3A1E" },
  burgundy: { name: "Bordeaux", hex: "#5C1A1B" },
  red: { name: "Rouge", hex: "#B0282A" },
  green: { name: "Vert", hex: "#2E5D3A" },
  blue: { name: "Bleu", hex: "#1F4C8C" },
  khaki: { name: "Kaki", hex: "#6B6A3E" },
  pink: { name: "Rose", hex: "#E9B7B7" },
} as const;

export const PRODUCTS: Product[] = [
  // ============= WOMEN — T-SHIRTS (from uploaded images) =============
  {
    id: "w-tee-louboutin",
    slug: "t-shirt-femme-christian-louboutin",
    name: "T-Shirt Christian Louboutin",
    description:
      "T-shirt femme en coton premium, imprimé motif escarpins haute couture. Coupe ajustée, col rond.",
    gender: "women",
    category: "t-shirts",
    price: DEFAULT_TEE_PRICE,
    images: ["/products/w-louboutin-white.jpg"],
    colors: [C.white],
    sizes: SIZES_APPAREL,
    inStock: true,
    featured: true,
    isNew: true,
  },
  {
    id: "w-tee-tommy-crest",
    slug: "t-shirt-femme-tommy-crest",
    name: "T-Shirt Tommy Hilfiger Crest",
    description:
      "T-shirt femme imprimé blason Tommy Hilfiger « Mode And Culture Italy ». Coton doux, coupe slim.",
    gender: "women",
    category: "t-shirts",
    price: DEFAULT_TEE_PRICE,
    images: ["/products/w-tommy-crest-white.jpg", "/products/w-tommy-crest-black.jpg"],
    colors: [C.white, C.black],
    sizes: SIZES_APPAREL,
    inStock: true,
    featured: true,
  },
  {
    id: "w-tee-vogue",
    slug: "t-shirt-femme-vogue-marilyn",
    name: "T-Shirt Vogue Marilyn",
    description:
      "T-shirt femme imprimé couverture Vogue iconique. 100% coton, finitions soignées.",
    gender: "women",
    category: "t-shirts",
    price: DEFAULT_TEE_PRICE,
    images: ["/products/w-vogue-white.jpg"],
    colors: [C.white],
    sizes: SIZES_APPAREL,
    inStock: true,
    isNew: true,
  },
  {
    id: "w-tee-ck",
    slug: "t-shirt-femme-calvin-klein",
    name: "T-Shirt Calvin Klein CK",
    description:
      "T-shirt femme Calvin Klein avec logo CK signature. Coton stretch, coupe féminine.",
    gender: "women",
    category: "t-shirts",
    price: DEFAULT_TEE_PRICE,
    images: ["/products/w-ck-white.jpg", "/products/w-ck-black.jpg"],
    colors: [C.white, C.black],
    sizes: SIZES_APPAREL,
    inStock: true,
    featured: true,
  },

  // ============= MEN — T-SHIRTS (from uploaded images) =============
  {
    id: "m-tee-ralph",
    slug: "t-shirt-homme-ralph-lauren",
    name: "T-Shirt Ralph Lauren",
    description:
      "T-shirt homme Ralph Lauren avec logo Polo emblématique. Coton peigné de qualité supérieure.",
    gender: "men",
    category: "t-shirts",
    price: DEFAULT_TEE_PRICE,
    images: ["/products/m-ralph-white.jpg", "/products/m-ralph-duo.jpg"],
    colors: [C.white, C.black],
    sizes: SIZES_APPAREL,
    inStock: true,
    featured: true,
    isNew: true,
  },
  {
    id: "m-tee-ck",
    slug: "t-shirt-homme-calvin-klein",
    name: "T-Shirt Calvin Klein CK",
    description:
      "T-shirt homme Calvin Klein avec grand logo CK. Coupe régulière, coton premium.",
    gender: "men",
    category: "t-shirts",
    price: DEFAULT_TEE_PRICE,
    images: ["/products/m-ck-duo.jpg"],
    colors: [C.navy, C.black],
    sizes: SIZES_APPAREL,
    inStock: true,
    featured: true,
  },
  {
    id: "m-tee-tommy-flag",
    slug: "t-shirt-homme-tommy-flag",
    name: "T-Shirt Tommy Hilfiger Flag",
    description:
      "T-shirt homme Tommy Hilfiger avec drapeau signature. Coton respirant, finition durable.",
    gender: "men",
    category: "t-shirts",
    price: DEFAULT_TEE_PRICE,
    images: ["/products/m-tommy-flag-duo.jpg"],
    colors: [C.black, C.grey],
    sizes: SIZES_APPAREL,
    inStock: true,
    isNew: true,
  },
  {
    id: "m-tee-hilfiger-laurel",
    slug: "t-shirt-homme-hilfiger-laurel",
    name: "T-Shirt Hilfiger Laurel EST 1985",
    description:
      "T-shirt homme Hilfiger imprimé laurier vintage « EST 1985 ». Coton lourd, look intemporel.",
    gender: "men",
    category: "t-shirts",
    price: DEFAULT_TEE_PRICE,
    images: ["/products/m-hilfiger-laurel-duo.jpg"],
    colors: [C.white, C.navy],
    sizes: SIZES_APPAREL,
    inStock: true,
    featured: true,
  },

  // ============= WOMEN — autres catégories =============
  {
    id: "w-shirt-poplin",
    slug: "chemise-femme-poplin",
    name: "Chemise Poplin Classique",
    description: "Chemise femme en popeline de coton, coupe oversize moderne.",
    gender: "women",
    category: "shirts",
    price: 49.9,
    images: ["/products/w-louboutin-white.jpg"],
    colors: [C.white, C.black, C.beige],
    sizes: SIZES_APPAREL,
    inStock: true,
  },
  {
    id: "w-jeans-mom",
    slug: "jean-femme-mom-fit",
    name: "Jean Mom Fit Taille Haute",
    description: "Jean femme taille haute, coupe Mom Fit, denim brut résistant.",
    gender: "women",
    category: "jeans",
    price: 69.9,
    images: ["/products/w-louboutin-white.jpg"],
    colors: [C.blue, C.black],
    sizes: ["34", "36", "38", "40", "42", "44"],
    inStock: true,
  },
  {
    id: "w-pants-cargo",
    slug: "pantalon-cargo-femme",
    name: "Pantalon Cargo Femme",
    description: "Pantalon cargo femme, coton stretch, multipoches.",
    gender: "women",
    category: "pants",
    price: 59.9,
    images: ["/products/w-ck-black.jpg"],
    colors: [C.khaki, C.black, C.beige],
    sizes: SIZES_APPAREL,
    inStock: true,
  },
  {
    id: "w-hoodie-essentials",
    slug: "hoodie-femme-essentials",
    name: "Hoodie Essentials Femme",
    description: "Sweat à capuche femme molletonné, coupe ample confort.",
    gender: "women",
    category: "hoodies",
    price: 54.9,
    images: ["/products/w-vogue-white.jpg"],
    colors: [C.cream, C.black, C.grey, C.burgundy],
    sizes: SIZES_APPAREL,
    inStock: true,
    isNew: true,
  },
  {
    id: "w-jacket-trench",
    slug: "trench-femme-classique",
    name: "Trench-Coat Classique",
    description: "Trench femme intemporel, coton gabardine, ceinture nouée.",
    gender: "women",
    category: "jackets",
    price: 149.9,
    images: ["/products/w-tommy-crest-white.jpg"],
    colors: [C.beige, C.black],
    sizes: SIZES_APPAREL,
    inStock: true,
    featured: true,
  },
  {
    id: "w-shoes-sneakers",
    slug: "sneakers-femme-low",
    name: "Sneakers Low Femme",
    description: "Baskets basses femme, cuir lisse, semelle blanche.",
    gender: "women",
    category: "shoes",
    price: 89.9,
    images: ["/products/w-ck-white.jpg"],
    colors: [C.white, C.black],
    sizes: ["36", "37", "38", "39", "40", "41"],
    inStock: true,
  },
  {
    id: "w-bag-tote",
    slug: "sac-tote-femme",
    name: "Sac Tote Premium",
    description: "Sac fourre-tout femme, simili-cuir, grande capacité.",
    gender: "women",
    category: "bags",
    price: 79.9,
    images: ["/products/w-louboutin-white.jpg"],
    colors: [C.black, C.brown, C.cream],
    sizes: ["Unique"],
    inStock: true,
  },
  {
    id: "w-watch-classic",
    slug: "montre-femme-classique",
    name: "Montre Classique Femme",
    description: "Montre analogique femme, bracelet acier, cadran minimaliste.",
    gender: "women",
    category: "watches",
    price: 129.9,
    images: ["/products/w-vogue-white.jpg"],
    colors: [{ name: "Or Rose", hex: "#B76E79" }, { name: "Argent", hex: "#C0C0C0" }],
    sizes: ["Unique"],
    inStock: true,
  },
  {
    id: "w-acc-belt",
    slug: "ceinture-cuir-femme",
    name: "Ceinture Cuir Femme",
    description: "Ceinture femme en cuir véritable, boucle métallique.",
    gender: "women",
    category: "accessories",
    price: 29.9,
    images: ["/products/w-ck-black.jpg"],
    colors: [C.black, C.brown],
    sizes: ["S", "M", "L"],
    inStock: true,
  },

  // ============= MEN — autres catégories =============
  {
    id: "m-shirt-oxford",
    slug: "chemise-homme-oxford",
    name: "Chemise Oxford Classique",
    description: "Chemise homme Oxford, coton tissé serré, col boutonné.",
    gender: "men",
    category: "shirts",
    price: 54.9,
    images: ["/products/m-ralph-white.jpg"],
    colors: [C.white, C.blue, C.black],
    sizes: SIZES_APPAREL,
    inStock: true,
    featured: true,
  },
  {
    id: "m-jeans-slim",
    slug: "jean-homme-slim",
    name: "Jean Slim Fit Homme",
    description: "Jean homme coupe slim, denim stretch confort.",
    gender: "men",
    category: "jeans",
    price: 74.9,
    images: ["/products/m-ralph-duo.jpg"],
    colors: [C.blue, C.black, C.grey],
    sizes: ["28", "30", "32", "34", "36", "38"],
    inStock: true,
  },
  {
    id: "m-pants-chino",
    slug: "pantalon-chino-homme",
    name: "Pantalon Chino Homme",
    description: "Chino homme coupe droite, coton stretch.",
    gender: "men",
    category: "pants",
    price: 59.9,
    images: ["/products/m-hilfiger-laurel-duo.jpg"],
    colors: [C.beige, C.navy, C.khaki, C.black],
    sizes: SIZES_APPAREL,
    inStock: true,
  },
  {
    id: "m-hoodie-classic",
    slug: "hoodie-homme-classic",
    name: "Hoodie Classic Homme",
    description: "Sweat à capuche homme, coton molletonné, capuche doublée.",
    gender: "men",
    category: "hoodies",
    price: 64.9,
    images: ["/products/m-ck-duo.jpg"],
    colors: [C.black, C.grey, C.navy, C.burgundy],
    sizes: SIZES_APPAREL,
    inStock: true,
    isNew: true,
  },
  {
    id: "m-jacket-bomber",
    slug: "bomber-homme",
    name: "Veste Bomber Homme",
    description: "Bomber homme aviateur, polyester technique, finition zip.",
    gender: "men",
    category: "jackets",
    price: 119.9,
    images: ["/products/m-tommy-flag-duo.jpg"],
    colors: [C.black, C.green, C.navy],
    sizes: SIZES_APPAREL,
    inStock: true,
    featured: true,
  },
  {
    id: "m-shoes-runner",
    slug: "sneakers-homme-runner",
    name: "Sneakers Runner Homme",
    description: "Baskets homme légères, mesh respirant, semelle EVA.",
    gender: "men",
    category: "shoes",
    price: 99.9,
    images: ["/products/m-ralph-white.jpg"],
    colors: [C.white, C.black, C.grey],
    sizes: SIZES_SHOES,
    inStock: true,
  },
  {
    id: "m-bag-backpack",
    slug: "sac-a-dos-homme",
    name: "Sac à Dos Urbain",
    description: "Sac à dos homme, compartiment laptop, polyester déperlant.",
    gender: "men",
    category: "bags",
    price: 69.9,
    images: ["/products/m-ck-duo.jpg"],
    colors: [C.black, C.navy, C.grey],
    sizes: ["Unique"],
    inStock: true,
  },
  {
    id: "m-watch-chrono",
    slug: "montre-homme-chrono",
    name: "Montre Chronographe Homme",
    description: "Montre chronographe homme, bracelet cuir, cadran trois compteurs.",
    gender: "men",
    category: "watches",
    price: 159.9,
    images: ["/products/m-ralph-duo.jpg"],
    colors: [C.black, C.brown],
    sizes: ["Unique"],
    inStock: true,
    featured: true,
  },
  {
    id: "m-acc-wallet",
    slug: "portefeuille-cuir-homme",
    name: "Portefeuille Cuir Homme",
    description: "Portefeuille homme en cuir véritable, multi-cartes.",
    gender: "men",
    category: "accessories",
    price: 39.9,
    images: ["/products/m-hilfiger-laurel-duo.jpg"],
    colors: [C.black, C.brown],
    sizes: ["Unique"],
    inStock: true,
  },
  {
    id: "m-other-cap",
    slug: "casquette-homme",
    name: "Casquette Logo Brodé",
    description: "Casquette homme baseball, coton, fermeture réglable.",
    gender: "men",
    category: "other",
    price: 19.9,
    images: ["/products/m-tommy-flag-duo.jpg"],
    colors: [C.black, C.white, C.navy, C.burgundy],
    sizes: ["Unique"],
    inStock: true,
  },

  // ============= KIDS =============
  {
    id: "k-tee-classic",
    slug: "t-shirt-enfant-classic",
    name: "T-Shirt Enfant Classic",
    description: "T-shirt enfant coton doux, coupe confortable.",
    gender: "kids",
    category: "t-shirts",
    price: 14.9,
    images: ["/products/m-ralph-white.jpg"],
    colors: [C.white, C.black, C.navy, C.red],
    sizes: SIZES_KIDS,
    inStock: true,
    featured: true,
  },
  {
    id: "k-shirt-poplin",
    slug: "chemise-enfant-poplin",
    name: "Chemise Enfant Popeline",
    description: "Chemise enfant en popeline, idéale occasions.",
    gender: "kids",
    category: "shirts",
    price: 29.9,
    images: ["/products/m-ralph-duo.jpg"],
    colors: [C.white, C.blue],
    sizes: SIZES_KIDS,
    inStock: true,
  },
  {
    id: "k-jeans-regular",
    slug: "jean-enfant-regular",
    name: "Jean Enfant Regular",
    description: "Jean enfant coupe régulière, denim confort.",
    gender: "kids",
    category: "jeans",
    price: 34.9,
    images: ["/products/m-hilfiger-laurel-duo.jpg"],
    colors: [C.blue, C.black],
    sizes: SIZES_KIDS,
    inStock: true,
  },
  {
    id: "k-pants-jogger",
    slug: "jogger-enfant",
    name: "Pantalon Jogger Enfant",
    description: "Jogger enfant molletonné, taille élastique.",
    gender: "kids",
    category: "pants",
    price: 24.9,
    images: ["/products/m-ck-duo.jpg"],
    colors: [C.grey, C.black, C.navy],
    sizes: SIZES_KIDS,
    inStock: true,
    isNew: true,
  },
  {
    id: "k-hoodie-fun",
    slug: "hoodie-enfant",
    name: "Hoodie Enfant Confort",
    description: "Sweat à capuche enfant, doublure douce.",
    gender: "kids",
    category: "hoodies",
    price: 34.9,
    images: ["/products/m-tommy-flag-duo.jpg"],
    colors: [C.grey, C.burgundy, C.navy],
    sizes: SIZES_KIDS,
    inStock: true,
  },
  {
    id: "k-jacket-puffer",
    slug: "doudoune-enfant",
    name: "Doudoune Enfant",
    description: "Doudoune enfant légère, capuche amovible.",
    gender: "kids",
    category: "jackets",
    price: 79.9,
    images: ["/products/m-ralph-duo.jpg"],
    colors: [C.black, C.red, C.navy],
    sizes: SIZES_KIDS,
    inStock: true,
    featured: true,
  },
  {
    id: "k-shoes-sneaker",
    slug: "sneakers-enfant",
    name: "Sneakers Enfant",
    description: "Baskets enfant, fermeture scratch, semelle souple.",
    gender: "kids",
    category: "shoes",
    price: 49.9,
    images: ["/products/m-ralph-white.jpg"],
    colors: [C.white, C.pink, C.navy],
    sizes: SIZES_KIDS_SHOES,
    inStock: true,
  },
  {
    id: "k-bag-backpack",
    slug: "sac-a-dos-enfant",
    name: "Sac à Dos Enfant",
    description: "Sac à dos enfant, parfait pour l'école.",
    gender: "kids",
    category: "bags",
    price: 34.9,
    images: ["/products/w-vogue-white.jpg"],
    colors: [C.pink, C.navy, C.red],
    sizes: ["Unique"],
    inStock: true,
  },
  {
    id: "k-acc-cap",
    slug: "casquette-enfant",
    name: "Casquette Enfant",
    description: "Casquette enfant ajustable, logo brodé.",
    gender: "kids",
    category: "accessories",
    price: 14.9,
    images: ["/products/m-tommy-flag-duo.jpg"],
    colors: [C.navy, C.red, C.black],
    sizes: ["Unique"],
    inStock: true,
  },
];

export const GENDER_LABELS: Record<Gender, string> = {
  women: "Femme",
  men: "Homme",
  kids: "Enfant",
};

export const CATEGORY_LABELS: Record<Category, string> = {
  "t-shirts": "T-Shirts",
  shirts: "Chemises",
  pants: "Pantalons",
  jeans: "Jeans",
  jackets: "Vestes",
  hoodies: "Hoodies",
  shoes: "Chaussures",
  bags: "Sacs",
  watches: "Montres",
  accessories: "Accessoires",
  other: "Autres",
};

export const CATEGORIES: Category[] = [
  "t-shirts",
  "shirts",
  "pants",
  "jeans",
  "jackets",
  "hoodies",
  "shoes",
  "bags",
  "watches",
  "accessories",
  "other",
];

export const GENDERS: Gender[] = ["women", "men", "kids"];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) => p.id !== product.id && p.gender === product.gender && p.category === product.category
  ).slice(0, limit);
}

export function formatPrice(price: number): string {
  return `${price.toFixed(3).replace(".", ",")} DT`;
}
